Add "Interim finance committee role"
astropy/astropy.github.com pull request #377
Opened 2020-05-10 21:46 UTC by hamogu

While the current finance committee is only "interim" and will hopefully
be replaced soon with a more permanent construct, this committee is
beyond the theoretical planning stage and is distributing real money.
That will have an impact on the the community one way or another.
In the interest of transparancy I think it is thus warrented at this point
to list the team members on the team page. At least that's where I would
look for it if I did not know whom to complain to ;-)

Given that it's "interim", I've placed the committee between the
"coordinators" and the "maintainers" on the page, but I suggest
revisiting that once the full Astropy governance structure is worked out.

2020-05-10 21:49 UTC, hamogu commented
@astrofrog @taldcroft @kelle @eteq @jdswinbank @crawfordsm

2020-05-13 17:00 UTC, astrofrog requested changes
Thanks for adding this! :+1:  A few comments below.

2020-05-13 17:00 UTC, astrofrog commented on roles.json
> +		"Paying and overseeing folks in supporting roles (e.g. documentation copy-editors, contract lawyers in service of 1, etc).",
folks -> people or individuals

also not sure what 'in service of 1' means

2020-05-13 17:44 UTC, hamogu commented on roles.json
> +		"Paying and overseeing folks in supporting roles (e.g. documentation copy-editors, contract lawyers in service of 1, etc).",
The text is taken from the email that announced the IFC a few months ago where the points were numbered and this refers back got point (1). I'll reword.

2020-05-13 17:53 UTC, hamogu commented on roles.json
> -        "role-head": "Documentation infrastructure maintainer",
fixed. I must have copied the learn coordinator to use as a template, but then actually used the docs maintainer to edit.

2020-05-13 17:53 UTC, hamogu commented on roles.json
> +		"Determine the process of paying folks the core dev team and other developers.",
done.

2020-05-13 19:54 UTC, eteq approved these changes
Some very minor wording changes which I'll just put in directly, but otherwise looks good.

2020-05-13 19:54 UTC, eteq commented on roles.json
> +		"Determine the process of paying people including project members.",
```suggestion
		"Determine the process for paying people from Astropy Project-level funding.",
```

2020-05-13 19:54 UTC, eteq commented on roles.json
> +		"Develop a transparent process for reporting all of the above to the Coordination Committee and wider community, related record keeping, and planning the same for future possible financial committe
```suggestion
		"Maintain and continuously develop a transparent process for reporting all of the above to the Coordination Committee and wider community, related record keeping, and planning the same for future possible financial committee efforts."
```

2020-05-13 19:54 UTC, merged