Add specreduce as a coordinated package
astropy/astropy.github.com pull request #489
Opened 2022-05-05 16:12 UTC by eteq

Following discussion at today's Astropy coordination meeting, there was consensus to add specreduce as a coordinated package given that it is referenced in the already-accepted [APE13](https://zenodo.org/record/1117943) and there's now a public release.

(Still needs CoCo approval, and @tepickering's :+1: to be listed as a maintainer)

2022-05-05 16:54 UTC, pllim commented on affiliated/registry.json
> +            "description": "Coordinated package to provide a data reduction toolkit for optical and infrared spectroscopy, on which applications such as pipeline processes for specific instruments ca
```suggestion
            "description": "Coordinated package to provide a data reduction toolkit for optical and infrared spectroscopy, on which applications such as pipeline processes for specific instruments can be built.",
```

2022-05-05 16:55 UTC, pllim commented
I am guessing this would bypass the process at https://github.com/astropy/astropy-project/blob/main/affiliated/affiliated_package_review_process.md ?

2022-05-05 16:59 UTC, tepickering commented
coordinated and affiliated packages have different processes, though?

2022-05-05 17:00 UTC, pllim commented
No idea! There is no policy on coordinated that I am aware of.

2022-05-05 17:05 UTC, tepickering commented
that is my impression as well. i guess putting it up for a vote at a coordination meeting counts as a policy, though.

2022-05-05 17:06 UTC, pllim commented
Whatever it is, maybe it should be formally documented going forward. 👀

2022-05-06 14:29 UTC, dhomeier commented
My understanding of the coordination meeting vote was of a decision whether to put it into the 'coordinated' or 'affiliated' category; at least that's what I intended to put on the agenda. Not necessarily to bypass the entire regular process, but if there is none in effect, we need to proceed based on that and the CoCo decision.
Actually my assumption was that the formal process paralleled the affiliated package review, as both have the same JSON fields to be filled in (where `coordinated` however is one of the two fields not documented in the guidelines... ;-).
But in this case I would have also gone along with @plim's comments above, i.e. review the formal criteria here without asking another reviewer (not lastly as most or all qualified core developers are probably in some way or another involved with `specreduce`).
Looking at the literal description in https://www.astropy.org/affiliated/index.html#coordinated-packages the destinguishing criterion would actually be
> the Astropy Project as a whole maintains them

which probably should be read as “their principal maintainers are all Astropy Core Team members and the the project as a whole assumes some responsibility for them”, since the current coordinated packages are still listed with individual maintainers.

In this case I propose to keep the PR open for a two-week period after I have added a review, similar to other role-related project PRs.

2022-05-06 16:43 UTC, dhomeier requested changes
My actual change request is for the package repo itself to add the CITATION file. Otherwise approved, pending the CoCo confirmation and possibly the suggested two-week comment period.

2022-05-06 16:43 UTC, dhomeier commented on affiliated/registry.json
> +                "testing": "Partial",
Looks a bit odd seeing this in the same category as e.g. `specutils` with 21 vs. some 500 CI tests. Which is not to say I see it as a show-stopper here, so it should stay Orange. I guess I'd rather place `specutils` at Yellow, but with only so many levels, things can probably stay as they are. Or is it time to promote `specutils` to Green – @pllim, I think you have some experience with unexpected/uncovered bugs there?

2022-05-06 16:43 UTC, dhomeier commented on affiliated/registry.json
> +                "documentation": "Partial",
The package should have instructions about citing (CITATION file), which we've been asking affiliated packages to add, and made mandatory now.

2022-05-06 16:59 UTC, pllim commented on affiliated/registry.json
> +                "testing": "Partial",
Re: specutils -- Re-reviewing it should be a separate issue?

2022-05-06 17:04 UTC, dhomeier commented on affiliated/registry.json
> +                "testing": "Partial",
Sure. Or maybe just a PR to update the `testing` field (and perhaps `documentation` as well)?

2022-05-06 17:17 UTC, pllim commented on affiliated/registry.json
> +                "testing": "Partial",
I would like specutils maintainers to comment: @nmearl @rosteen @keflavich @eteq (as listed on the repo)

2022-05-06 17:19 UTC, hamogu commented
APE 0 says for the role of the Coco:
>>> - Seek consensus among the Astropy community, particularly before acting in a formal capacity,
>>> - Act as the decision-making body where all other methods for achieving consensus have failed,

and later 
>>> Delegate parts of their authority to other subcommittees or processes.

In this cases we had a clear consensus at the Coordination meeting and the affiliated package editors are hard at work to ensure that coordinates packages follow at least the same standards as affiliated packages, so I personally (this disagrees with @eteq view in  https://github.com/astropy/astropy.github.com/pull/489#issue-1226901238) don't think any Coco action is required. In my view, this can simply be merged, once the comments above are addressed and the affiliated package editors are happy.

2022-05-06 17:52 UTC, dhomeier commented
> In this cases we had a clear consensus at the Coordination meeting and the affiliated package editors are hard at work to ensure that coordinates packages follow at least the same standards as affiliated packages, so I personally (this disagrees with @eteq view in [#489 (comment)](https://github.com/astropy/astropy.github.com/pull/489#issue-1226901238)) don't think any Coco action is required. In my view, this can simply be merged, once the comments above are addressed and the affiliated package editors are happy.

Happy to proceed without further action from the CoCo; however “at least the same standards” would imply an independent review; foregoing this I still vote for the comment period, given the collaborative maintainer role taken by the Project.

2022-06-02 15:24 UTC, hamogu commented
The Coco discussed this and agrees on coordinated package (no surprise!). So, this can be merged by the package editors when all concerns by @pllim and @dhomeier are addressed.

2022-06-02 15:36 UTC, dhomeier commented
Only waiting for astropy/specreduce#108 then, I think.

2022-06-02 23:57 UTC, dhomeier commented
Thanks for bringing in astropy/specreduce#110 ; I have sent out the mail to start the 2-week comment period! I encourage you to finalise the author list in parallel.

2022-06-24 21:41 UTC, dhomeier commented
Thanks for merging the CITATION file @tepickering. The comment period has also (well) passed; welcome to the team of coordinated packages and congratulations!

2022-06-24 21:41 UTC, merged