Roles: Remove sub-role for Learn Team
astropy/astropy.github.com pull request #525
Opened 2023-03-06 23:12 UTC by pllim

I think it is a little overkill to have so many sub-roles for Learn Team. Infrastructure staff maintains multiple packages across the board (and manages releases for them too, etc) and yet we do not list all those packages on this page.

This PR eliminates sub-role for Learn Team but kept them in parenthesis since I also notice you have sub-responsibility. This is not ideal but it is getting late and I cannot think of anything better. Ideas welcome. If we can make this more fluid, then when you move Learn staff around the team, you don't have to constantly come back to update this page.

Affected people in this listing:

* @eblur 
* @kelle 
* @adrn 
* @mwcraig 
* @eteq 
* @jonathansick
* @stargaser
* @bmorris3

2023-03-07 01:28 UTC, hamogu commented
The learn team seems to coordinate within themselves with regular telecons. Also, I think several people are stepping back from active engagement, so maybe this is time to restructure it and summary a bit.

2023-03-07 05:21 UTC, pllim commented
@kelle , I don't know how I feel about the duplicated info but I opened https://github.com/astropy/astropy-project/pull/332 to address your request. As long as we remember to keep them in sync...

2023-03-07 16:26 UTC, jonathansick commented
> @jonathansick , is [astropy/learn-astropy#71](https://github.com/astropy/learn-astropy/issues/71) sufficient for follow-up? I get confused now between `astropy-tutorials` and `learn-astropy`. Is this the correct repo?

@pllim Thanks for making those issues! astropy/astropy-tutorials is content-oriented and astropy/learn-astropy is infrastructure-oriented so that's a good expression of the editorial vs infrastructure sub-roles for example.

2023-03-20 17:20 UTC, eteq requested changes
See my inline comment about workshop role.  But also I feel like the discussion #524 applies here - that there *is* value in ensuring we don't lose the information of all the work. Should we maybe just copy over the info here?

2023-03-20 17:20 UTC, eteq commented
(I had to do something a bit weird in the suggestion there, so @pllim , if you accept that you'll definitely want to wait for the CI to be sure I didn't break teh JSON)

2023-05-03 20:05 UTC, hamogu commented
After discussion in the Coordination meeting, we believe that it's worthwhile to have relatively fine-grained roles, even if they might be unfilled. Names should be updated (or be replaced by "unfilled") in a separate PR.

2023-05-03 20:05 UTC, closed without merging