Add strategic planning role
astropy/astropy.github.com pull request #584
Opened 2024-04-29 18:31 UTC by eteq

This came out of some discussions the CoCo has been having the last few months on whose role it is to do big picture planning.  We eventually settled on the reality of the current situation: that it has historically been something the CoCo does, but it is not *necessary* that this be so, and we should make it an explicit role so others can participate if they want.

As a starting point I named the people as just "the CoCo members" since that's the current reality, but that could change if others want to lean in on this topic.

2024-04-30 13:59 UTC, hamogu commented
I would suggest to leave this open to the coordination meeting. A lot of strategic planning should happen there! Personally, I'm also interested in these things. However, there is a question of how we organize in practice. In my experience, strategic planning is one of those things that profit from real-time talk (in person or on zoom), unlike, e.g. subpackage maintaining (which can be done fine asynchronosly on GH). 
Maybe dedicate one Coco meeting or one dev telecon every other months (because in practice this overlaps with Coco membership and interested developer membership) to strategic planning and open it to all interested parties?

2024-04-30 14:01 UTC, pllim commented
Given the meeting is less than 2 months away, sure, we can wait. I added to ideas here:

* https://github.com/astropy/astropy-project/issues/349#issuecomment-2085419701

2024-04-30 14:02 UTC, pllim requested changes
One member expressed desire to wait till Coordination meeting, so I am blocking merge for now. Thanks!

2024-05-01 07:29 UTC, astrofrog commented
Just an idea - it seems this would effectively be a steering committee? If so it might be worth considering using a name like this so that it is more familiar for external people, if it becomes an entity that does grow beyond the CoCo.

2024-05-02 15:47 UTC, eteq commented
Oh, and @hamogu , re-reading your message, I'm not clear on this: were you saying we should discuss *whether to create this role* at the coordination meeting (as @pllim interpreted it) or that this role should partly be *done* by the coordination meeting (as I interpreted it).  Or both?  Just trying to understand if you were saying action on this should wait on the meeting or not.

(In practice it probably doesn't really matter, since the CoCo is already likely to bring up the strategic items at the meeting as it stands, but I think it will make it slightly easier to recruit folks at the coordination meeting if this roles exists by then since we can say "do you want to join the group?" rather than "do you want to join a group that may or may not exist?")

2024-05-02 15:57 UTC, eteq commented
Answering my own question - out-of-band (in the developer telecon) @hamogu said the answer was "both" - which I am totally fine with, just wanted the clarification.

2024-05-02 15:59 UTC, hamogu commented
The coordination meeting does fill this role - that's what it is for. So, that should be reflected in the description of the role (e.g. "stratetic planning in between coordination meetings" or "monitoring ... as set by coordination meetings".

But I *also* think that this role should be created at the coordination meeting. It's more open and inclusive to ask for interested parties there, than to pre-fill the role with default names first.

2024-05-02 17:27 UTC, pllim commented
So this is more like "strategic plans enforcer" instead of "strategic planning"? 🤔

2024-05-02 20:33 UTC, astrofrog commented
Ok so a few thoughts having taken a bit more time to digest this:

* @eteq - I agree that steering committee isn't right because given the range of definitions out there it doesn't really distinguish it from coordination committee.
* Should the role being proposed here be called a 'group' or a 'committee'? For example 'Strategic Planning Committee' or 'Strategic Planning Group'. It's likely it would operate as a group or committee rather than individual people with a role acting independently?
* One of the things that's I've been wondering how we could improve is that indeed beyond the CoCo, any kind of strategic planning is restricted to (at most) once a year for other project members. If strategic planning was done as a committee, it could be a way of increasing participation throughout the year.

@eteq - you said 'could happen at coordination meetings and dev telecons' - I guess we should think about whether to treat the dev telecons as mini coordination meetings in the sense they could also cover strategic stuff and non-development things, or keep the dev telecons be about dev and have separate calls for strategic planning?

2024-06-11 14:07 UTC, Cadair reviewed
Following the discussion at the coordination meeting I think this is a good thing to have, but this committee has a very important remit so I think the wording of this charter is important to get right.

So here's a bunch of word-smithing.

2024-06-11 14:07 UTC, Cadair commented on roles.json
> +                "Shape and provide a vision for next major steps in the Project, in consultation with the whole Astropy community.",
Isn't this just the roadmap?

2024-06-11 14:07 UTC, Cadair commented on roles.json
> +                "Monitor efforts on the topic above to ensure they are being done as imagined.",
```suggestion
                "Monitor project activities to see how well aligned with the roadmap and strategic goals of the project, and report back to the CoCo and community.",
```

2024-06-11 14:07 UTC, Cadair commented on roles.json
> +                "Maintain a large-scale view of the project (both from developer and user perspectives).",
This feels vague, could we add something about to what end here?

```suggestion
                "Maintain an overview of all the project activities (both from developer and user perspectives).",
```

2024-06-11 14:11 UTC, Cadair commented on roles.json
> +        "role": "Strategic Planner",
I think there is general consensus at the coordination meeting that this *must* be a committee.

```suggestion
        "role": "Strategic Planning Committee",
```

2024-06-11 14:16 UTC, eteq commented
A few highlights from the coordination meeting discussion (NOT COMPLETE - these are highlights and distillation from my perspective):

* a lot of agreement strategic planning is important, and that it needs multiple people to do it effectively
* maybe not *too* many, although exactly what that is is a bit ambiguous.
* There is actually a fair amount of interest - in the coordination meeting ~9 hands went up as possibly interested.
* Might need more clarification is that this role is a *devolved* role from the CoCo, since APE0 sort of says this is a CoCo role.
* There is a cross-connection with #89 in that the long-term view of this community is intertwined with how long-term the CoCo terms are.

2024-06-11 14:16 UTC, adrn commented on roles.json
> +                "Shape and provide a vision for next major steps in the Project, in consultation with the whole Astropy community.",
I missed the roadmap discussion, but it does sound like the roadmap in its current form. But IMO some of the vaguer elements of the roadmap as they currently stand should be removed from the roadmap and added to the charge of this group, and the roadmap should be a set of actionable items with timelines associated.

2024-06-11 14:25 UTC, adrn commented on roles.json
> +        "role": "Strategic Planner",
To be consistent with other names on the team page, I think:
```suggestion
        "role": "Strategic Planning Committee Member",
```

2024-06-11 14:32 UTC, Cadair commented on roles.json
> +            ]
```suggestion
                "Engage with, and collect input from, the the whole Astropy Community on project vision and priorities."
            ]
```

2024-09-30 15:20 UTC, eteq commented
Alright, this has all been cleaned up, reflecting various feedback both here and the coordination meeting, and should be ready to merge.

2024-10-28 16:32 UTC, merged

2024-10-28 16:32 UTC, ceb8 commented
Thanks @eteq !